### ISSUE TITLE
On opening OSC Unity Example file

### ISSUE THREAD

**Issue by Ansahmadiba** [thomasfredericks/UnityOSC#1]
Following are the errors while opening the OSC unity example package:
Assets/OSC/OSC.cs(124,14): error CS0101: The namespace `global::' already contains a definition for `UDPPacketIO'

Assets/OSC/OSC.cs(306,16): error CS0101: The namespace `global::' already contains a definition for `OscMessage'

Assets/OSC/OSC.cs(365,24): error CS0101: The namespace `global::' already contains a definition for `OscMessageHandler'

Assets/OSC/OSC.cs(385,16): error CS0101: The namespace `global::' already contains a definition for `OSC'

**Comment by thomasfredericks** [comment]
What version of Unity are you using and what is your OS ?

**Comment by thomasfredericks** [comment]
I cannot replicate this error. Are you importing the package twice?

**Comment by Ansahmadiba** [comment]
My Unity version is 5.5.2 and OS Windows. I imported the package once.

**Comment by thomasfredericks** [comment]
The package is already in the example. So no need to import.

**Comment by thomasfredericks** [comment]
The instructions are for new projects. Maybe that is confusing. The example runs without any modification.
