### ISSUE TITLE
Sending lists from Max

### ISSUE THREAD

**Issue by autofasurer** [thomasfredericks/UnityOSC#14]
Any tips on how to implement receiving a list from Max? 
I'm sending a list of positions which I'd love to turn into an array in Unity.

**Comment by thomasfredericks** [comment]
In Max, if you send /yo 1.0 2.0 3.0 it will send an OSC message with the address "/yo" followed by three integers. So you simply need to make three calls to GeFloat() as document in http://thomasfredericks.github.io/UnityOSC/ (see the /CubeXYZ example).

**Comment by autofasurer** [comment]
Cheers. My list is longer so I didn't want to go that route. But it's possible to cast the ArrayList that is message.values to an array so that solved the issue. 
Sorry to bug you with that stupid question, my c# skills are virtually non-existent. 

`float[] myArray= (float[]) message.values.ToArray(typeof(float));`
