### ISSUE TITLE
OSC Receive not working for me

### ISSUE THREAD

**Issue by sjaugmented** [thomasfredericks/UnityOSC#16]
I've got this in Start():
```
GameObject.FindGameObjectWithTag("OSC").GetComponent<OSC>().SetAddressHandler(addressBasic1 + "/receive", OnReceiveOSC);
GameObject.FindGameObjectWithTag("OSC").GetComponent<OSC>().SetAllMessageHandler(OnReceiveOSC);
```

And here's the OnReceive function:
```
void OnReceiveOSC(OscMessage message)
        {
            Debug.Log("OSC received: " + message);
            StartCoroutine("PlayParticles");
        }
```

Not getting anything though on either. Ports seem to be configured fine as the app is sending OSC just fine, just not receiving.

**Comment by thomasfredericks** [comment]
Based on previous issues, if you do not get any compile errors it is most often a configuration (ip or port) error.

**Comment by elewint** [comment]
Not sure if you resolved this already, but I had the same issue because my PC's WiFi network profile was set to "Public" rather than "Private." I guess my network firewall was blocking the incoming OSC messages.

**Comment by sjaugmented** [comment]
I've gotten it working in Unity by switching from being bootcamped on an iMac to an actual windows laptop. However, it's still not working in the Hololens 2, but my guess it has nothing to do with the actual plug in at this point.

I don't know - something about the iMac wasn't playing nice. I never figured out what though.
