### ISSUE TITLE
Send String

### ISSUE THREAD

**Issue by shahanrayqube** [thomasfredericks/UnityOSC#22]
How to send string in OSC?
I am able to send integers and floats but how to i send a string?
This works: message.values.Add(Random.Range(0, 1000));
This does not work: message.values.Add("This is my string");

**Comment by thomasfredericks** [comment]
Hi,

The only supported functions are the ones in the documentation: http://thomasfredericks.github.io/UnityOSC/
Hence, UnityOSC does not support Strings.

Note that I do not update or support UnityOSC anymore. Please use the following libraries instead:
* [Iam1337/extOSC: extOSC is a tool dedicated to simplify creation of applications in Unity with OSC protocol usage.](https://github.com/Iam1337/extOSC)
* [keijiro/OscJack: Lightweight C# implementation of OSC server/client](https://github.com/keijiro/OscJack)
* [keijiro/OscJackVS: OSC plugin for Unity Visual Scripting](https://github.com/keijiro/OscJackVS)
