### ISSUE TITLE
receiving only from localhost in last Unity3D

### ISSUE THREAD

**Issue by moebiussurfing** [thomasfredericks/UnityOSC#5]
hey @thomasfredericks  thanks for this addon!

I am running the example to move the boxes and its working fine in localhost.
The 'sending position on update' box is sending ok and i am receiving the 3 values on another machine/ip.
I set the 'Out IP' and 'Out Port' on the Osc object gui.

When I send the values to move the 'receive position' box from the other machine, the box isn't receiving the values. If i send the values from the same app but running on same machine (localhost) it works fine... 'In port' is the same in both cases.

this behaviour has any sense to you? 

There's any way to debug all OSC messages that is Unity receiving?

**Comment by moebiussurfing** [comment]
....also, if i put another OSC app listening on the same port, and same machine where Unity is running,
this app can receive fine all the osc messages from the another machine...

should I modify some code from the scripts?

My Unity version is 2017.3.0f3 and Windows10

**Comment by thomasfredericks** [comment]
@moebiussurfing Hi, I just tested the example with Cycling Max and Unity 2017.3.0f3 and it worked.

**Comment by moebiussurfing** [comment]
thanks for the fast reply @thomasfredericks 
solved! the problem was the windows firewall. Network was detected as public and changing it to private made the profile of the firewall enabling incomming connections (after accept the prompt request window)
