### ISSUE TITLE
playmodeStateChanged warning

### ISSUE THREAD

**Issue by GregFinger** [thomasfredericks/UnityOSC#6]
Just wanted to let you know that Unity 2017.3 is showing the warning

`Assets/OSC/OSC.cs(440,33): warning CS0618: UnityEditor.EditorApplication.playmodeStateChanged' is obsolete: Use EditorApplication.playModeStateChanged and/or EditorApplication.pauseStateChanged'`

**Comment by thomasfredericks** [comment]
Thank you. Noted.

**Comment by thomasfredericks** [comment]
Fixed in latest commit.
