### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jminor** [thomasfredericks/UnityOSC#9]
Hi. Your license file says you couldn't find the license for MakingThings's Make Controller OSC C# implementation. I think this is what you were looking for:

https://code.google.com/archive/p/makecontroller/
and here:
https://web.archive.org/web/20121021044334/http://www.makingthings.com:80/ref/firmware/html/group___o_s_c.html

Both state that their code is licensed under the Apache License 2.0.
I hope that is helpful :)
Also, thanks for making UnityOSC!

**Comment by thomasfredericks** [comment]
Thank you. I added the information to the LICENSE file.
